### ISSUE TITLE
All curated gene-disease associations from DisGeNET

### ISSUE THREAD

**Issue by ZhangYi0621** [liseda-lab/KGE_Predictions_GD#1]
Hello!
     Thanks for your excellent work.  And I saw you obtained all curated gene-disease associations from DisGeNET,  I can't find it in the original website, can you share the complete file with me?
     Thanks a  lot! my email is zy97@whut.edu.cn

**Comment by SusanaPNunes** [comment]
Hello!
I attached the complete version of the dataset I used. I will also add it for future reference on the GitHub page under the name 'curated_Disgenet.csv'
[curated_Disgenet.csv](https://github.com/liseda-lab/KGE_Predictions_GD/files/9813911/curated_Disgenet.csv)

**Comment by ZhangYi0621** [comment]
> 

Thanks a lot~
Best wishes!
