### ISSUE TITLE
Where is the ontology file?

### ISSUE THREAD

**Issue by missyoudaisy** [liseda-lab/KGE_Predictions_GD#2]
Hello!
Thanks for your excellent work. I just wonder, in section 2.2 "OPA2Vec", where is the ontology file in owl format? And what is the ROBOT tools?

**Comment by SusanaPNunes** [comment]
Hello, the ontology file in owl format is too big for GitHub, so it is not uploaded. For the Human Phenotype ontology, use its website https://hpo.jax.org/app/data/ontology. If you intend to use the two ontologies, here is the site for the gene ontology download  http://geneontology.org/docs/download-ontology/. 

The ROBOT tool http://robot.obolibrary.org/ is just a suggestion that allows for operations on ontologies, such as merging two ontology files into one single file, which can be useful for the opa2vec embedding.

**Comment by missyoudaisy** [comment]
> 

thank you~
